name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install npm
        working-directory: ./test
        run: npm ci
      - name: Trigger toolchain installation
        working-directory: ./test
        run: cargo fetch
      - name: Run tests
        working-directory: ./test
        run: npm test
